### ISSUE TITLE
TODO: Prelim Research

### ISSUE THREAD

**Issue by banditelol** [banditelol/daku#1]
- [ ] Cek API producthunt gimana untuk implement sendiri
- [ ] Cari alternatif untuk nyimpen si preferens "tinder" nya
- [ ] Apakah ada opsi lain?
- [ ] Coba cari metrics selain upvotes untuk melihat produk2 yang underdog
- [ ] Coba pelajari flutter nya kalau sempat
- [ ] Pengen implement ini make svelte sih
